name: WiX Docker Publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}/${{ secrets.DOCKERHUB_IMAGENAME }}

      - name: Modify Tag
        id: modifytag
        run: |
          IFS=',' read -ra TAGS_ARRAY <<< "${{ steps.meta.outputs.tags }}"
          NEW_TAGS=()
          for tag in "${TAGS_ARRAY[@]}"; do
              NEW_TAGS+=("${tag}-wix")
          done
          echo "newtags=$(IFS=,; echo "${NEW_TAGS[*]}")" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.modifytag.outputs.newtags }}
          file: Dockerfile.wix
