openai_api_key = "YourKey"
pinecone_api_key = "YourKey"
pinecone_environment = "YourENV"
pinecone_index = "YourIndex"
xata_api_key = "YourKey"
xata_db_url = "YourURL"
langchain_verbose = true
llm_model = "YourModel"
sensitivity_check = true
anonymous_allowed = true
password = "YourKey"
wix_oauth = false
wix_client_id = "YourID"